rtcStats:
    # File format header version to generate.
    fileFormat: 3

server:
    # HTTP port to listen on.
    httpPort: 8080
    # HTTP upload path where complete files can be uploaded.
    # Alternative to Websockets, disabled by default and only enabled
    # when the path is set. Typically starts with a '/'.
    httpUploadPath:
    # Directory where files are being stored while the websocket is still active.
    workDirectory: work
    # Directory where files are stored after preprocessed and when ready to upload.
    uploadDirectory: upload
    # Setting these to false is useful in dev environments where one needs to look at the generated files.
    deleteAtStart: true
    deleteAfterUpload: true
    # Whether to obfuscate IP addresses for privacy reasons.
    obfuscateIpAddresses: true
    # Maximum number of processes to use in parallel.
    # Upper bound (and default) is number of CPU cores.
    # In development only a single process is used.
    numberOfProcesses: 0

authorization:
    # JWT secret key to use for authorizing clients. If not set, no authorization is performed.
    jwtSecret:

maxmind:
    # Maxmind is used to provide geolocation together with ip address obfuscation
    # This can be downloaded with an account id and license key using
    # wget \
    # --user=$MAXMIND_ACCOUNT_ID \
    # --password=$MAXMIND_LICENSE_KEY \
    # https://download.maxmind.com/geoip/databases/GeoLite2-City/download?suffix=tar.gz -O GeoLite-City.mmdb.tgz && tar -xzf GeoLite-City.mmdb.tgz && mv GeoLite2-City*/GeoLite2-City.mmdb .
    path:
    
storage:
    # Amazon S3 based storage (or compatible APIs like supabase).
    s3:
        # compat option, required e.g. on supabase.
        forcePathStyle: false
        credentials:
            accessKeyId:
            secretAccessKey:
        region:
        endpoint:
        bucket:

database:
    # Database settings, postgres and supabase primarily.
    postgres:
        tableName: internals
        connectionString:
        ssl: # https://node-postgres.com/features/ssl
            # For Supabase, one needs to download the CA certificate as described
            # on https://supabase.com/docs/guides/platform/ssl-enforcement
            capath: # path to root cert.
            mode: # e.g. 'verify-full'.
